Numpy module

In [ ]:
''' Import the NumPy library using its standard alias.
Write the Python statement to import the NumPy library so that you can refer to it as 'np' in your code.'''
import numpy as np

In [1]:
'''Create a 1D array from a Python list.
Given the Python list `my_list = [10, 20, 30, 40, 50]`, convert it into a standard 1D NumPy
array and print the result. '''
import numpy as np
my_list = [10, 20, 30, 40, 50]
arr = np.array(my_list)
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [ ]:
''' Generate an array with a range of numbers.
Use a built-in NumPy function to create an array containing all integers from 5 to 15
inclusive. (Hint: Look into `np.arange`).'''
import numpy as np
arr = np.arange(5, 16)
print(arr)

[ 5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
''' Find array properties (Size and Shape).
Create any 1D NumPy array containing 6 elements. Write code to print its shape and the
total number of elements using array attributes.'''
import numpy as np

# Create a 1D NumPy array with 6 elements
arr = np.array([10, 20, 30, 40, 50, 60])

# Print shape of the array
print("Shape of array:", arr.shape)

# Print total number of elements
print("Total number of elements:", arr.size)

Shape of array: (6,)
Total number of elements: 6


In [ ]:
''' Element-wise arithmetic operations.
Create a NumPy array `arr = np.array([1, 2, 3, 4])`. Write code to multiply every element in
this array by 5, and then print the updated array. '''

import numpy as np

# Create the NumPy array
arr = np.array([1, 2, 3, 4])
arr = arr * 5
print("Updated array:", arr)

Updated array: [ 5 10 15 20]


In [ ]:
''' Accessing specific elements (Indexing).
Given the array `data = np.array([12, 24, 36, 48, 60])`, write a code snippet to print the first
element and the last element using indexing. '''

import numpy as np
data = np.array([12, 24, 36, 48, 60])
print(data[0],data[-1])

12 60


In [ ]:
''' Extracting a sub-array (Slicing).
Given the array `numbers = np.array([5, 10, 15, 20, 25, 30])`, use slicing to extract a new
array containing the middle elements: `[15, 20, 25]`.'''
import numpy as np
numbers = np.array([5, 10, 15, 20, 25, 30])
print(numbers[2:5])

[15 20 25]


In [ ]:
''' Create an array of all zeros.
Write a line of code to create a 1D NumPy array of size 8 where every element is a floating
point zero (0.0).'''
import numpy as np
arr = np.zeros(8)

print(arr)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
''' Create a sequence of evenly spaced numbers.
Use `np.linspace` to create an array of 5 evenly spaced numbers starting from 0 and ending
at 1. '''
import numpy as np
arr = np.linspace(0, 1, 5)

print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
''' Basic statistical functions.
Given the array `scores = np.array([85, 90, 78, 92, 88])`, find and print its mean (average)
value and its maximum value using built-in NumPy methods.'''
import numpy as np
scores = np.array([85, 90, 78, 92, 88])

mean_value = scores.mean()
max_value = scores.max()

print("Mean value:", mean_value)
print("Maximum value:", max_value)

Mean value: 86.6
Maximum value: 92


In [ ]:
''' Reshaping a 1D array into a 2D matrix (Intermediate).
Create a 1D NumPy array containing numbers from 1 to 12. Use the `.reshape()` method to
convert this array into a 2D matrix with 3 rows and 4 columns. Print both the reshaped
matrix and its new shape.'''
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
matrix = arr.reshape(3, 4)

print("Reshaped Matrix:")
print(matrix)

print("Shape of matrix:", matrix.shape)

Reshaped Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of matrix: (3, 4)


In [ ]:
''' Conditional filtering/Boolean Indexing (Intermediate).
Given the array `ages = np.array([14, 22, 17, 35, 19, 42, 15, 28])`, write a code snippet using
Boolean Indexing to filter out and display only the ages that are greater than or equal to 18.'''
import numpy as np
ages = np.array([14, 22, 17, 35, 19, 42, 15, 28])
adult_ages = ages[ages >= 18]


print("Ages >= 18:", adult_ages)

Ages >= 18: [22 35 19 42 28]


In [ ]:
''' Extracting rows and columns from a 2D Matrix (Intermediate).
Given the 2D array:
`matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])`
Write code to slice and extract: (a) The entire second row, and (b) The entire third column.'''
import numpy as np
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(matrix[1, :])
print(matrix[:, 2])

[40 50 60]
[30 60 90]


In [ ]:
''' Array broadcasting logic (Intermediate).
Create a 2D NumPy array of shape (2, 3) filled with ones. Add a 1D array of shape (3,)
containing `[1, 2, 3]` to it. Explain briefly how NumPy's broadcasting mechanism handles this
addition, and display the final matrix.'''
import numpy as np
arr2d = np.ones((2, 3))
arr1d = np.array([1, 2, 3])
result = arr2d + arr1d

print("Final Matrix:")
print(result)

Final Matrix:
[[2. 3. 4.]
 [2. 3. 4.]]


In [ ]:
''' Replacing elements based on conditions (Intermediate).
Given an array `temperatures = np.array([25, -2, 18, -5, 30, 0, 12])`, write a single line of
NumPy code using `np.where()` to replace all negative numbers with `0` while leaving the
positive numbers completely unchanged. '''
import numpy as np

temperatures = np.array([25, -2, 18, -5, 30, 0, 12])
temperatures = np.where(temperatures < 0, 0, temperatures)

print(temperatures)

[25  0 18  0 30  0 12]


In [ ]:
# determine different dimensions of array
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

0
1
2
3
[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
# accessing element and doing operations
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[2] + arr[3])

rr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', rr[0, 1])
print('5th element on 2nd row: ', rr[1, 4])
print('Last element from 2nd dim: ', rr[1, -1])

arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr3[0, 1, 2])

1
7
2nd element on 1st row:  2
5th element on 2nd row:  10
Last element from 2nd dim:  10
6


In [ ]:
# slicing array
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

#slicing 2 dimension array
rr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(rr[1, 1:4])
print(rr[0:2, 2])
print(rr[0:2, 1:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]
